Repository profluiscaparroz/estrutura-dados-c, pull requests merged in 2025-02, with the labels that each got.

#2 Resolve ticket #1
  README.md
  src/01-introducao-c/aula01/00_exemplo_encontra_raiz.c
  src/01-introducao-c/aula01/01_introducao_variaveis.c
  src/01-introducao-c/aula01/02_introducao_conversao_tipos.c
  src/docs/01-introducao-c/introducao.md
  src/docs/01-introducao-c/introducao.pdf
  src/docs/01-introducao-c/introducao_tipos_c.md
  src/docs/01-introducao-c/introducao_tipos_c.pdf
  src/docs/README.pdf
Labels: documentation, good first issue, aula

#4 Adiciona novos exemplos de conceitos
  src/01-introducao-c/aula01/03_exemplo_struct.c
  src/01-introducao-c/aula01/04_exemplo_constantes.c
  src/01-introducao-c/aula01/05_exemplo_booleano.c
  src/01-introducao-c/aula01/06_exemplo_escopo.c
  src/01-introducao-c/aula01/07a_exemplo_string.c
  src/01-introducao-c/aula01/07b_exemplo_string.c
  src/01-introducao-c/aula01/08_exemplo_ponteiros.c
  src/01-introducao-c/aula01/exercicio/exercicio1.c
  src/docs/01-introducao-c/introducao_ponteiros.md
  src/docs/01-introducao-c/introducao_string_c.md
  src/docs/01-introducao-c/introducao_string_c.pdf
Labels: documentation, aula

#6 Implementa o que foi pedido em #5
  README.pdf
  docs/01-introducao-c/Introducao_variavel_estaticos.md
  docs/01-introducao-c/Introducao_variavel_estaticos.pdf
  docs/01-introducao-c/README.md
  docs/01-introducao-c/introducao.pdf
  docs/01-introducao-c/introducao_booleano.md
  docs/01-introducao-c/introducao_booleano.pdf
  docs/01-introducao-c/introducao_constante.md
  docs/01-introducao-c/introducao_constante.pdf
  docs/01-introducao-c/introducao_ponteiros.md
  docs/01-introducao-c/introducao_string_c.md
  docs/01-introducao-c/introducao_string_c.pdf
  docs/01-introducao-c/introducao_tipos_c.md
  docs/01-introducao-c/introducao_tipos_c.pdf
  docs/01-introducao-c/introducao_variaveis.md
  docs/01-introducao-c/introducao_variaveis.pdf
  docs/01-introducao-c/introdução_escopo.md
  docs/01-introducao-c/introdução_escopo.pdf
  docs/02-controle-fluxo/controle-fluxo-lacos.md
  docs/02-controle-fluxo/controle-fluxo-lacos.pdf
  docs/02-controle-fluxo/controle-fluxo.md
  docs/02-controle-fluxo/controle-fluxo.pdf
  docs/02-controle-fluxo/operadores-relacionais.md
  docs/02-controle-fluxo/operadores-relacionais.pdf
  src/01-introducao-c/aula01/06_variaives_estaticas.c
  src/01-introducao-c/aula01/07_exemplo_escopo.c
  src/01-introducao-c/aula01/08_exemplo_ponteiros.c
  src/01-introducao-c/aula01/exercicio/exercicio2.c
  src/01-introducao-c/aula01/exercicio/exercicio3.c
  src/01-introducao-c/aula02/01_exemplo_operadores.c
  src/01-introducao-c/aula02/02_exemplo_controle_fluxo.c
  src/01-introducao-c/aula02/03_exemplo_laco_repeticao.c
  src/01-introducao-c/aula02/04_exemplo_salto.c
  src/01-introducao-c/aula02/05_exemplo_ponteiros.c
  src/01-introducao-c/aula02/06a_exemplo_string.c
  src/01-introducao-c/aula02/06b_exemplo_string.c
  src/01-introducao-c/aula02/exercicio/exercicioContaVogaisConsoante.c
  src/01-introducao-c/aula02/exercicio/exercicioSomaMultiplo.c
  src/01-introducao-c/aula02/exercicio/exerciciosSimples.c
Labels: aula

#7 Adiciona README explicativo
  docs/01-introducao-c/Introducao_variavel_estaticos.md
  docs/01-introducao-c/Introducao_variavel_estaticos.pdf
  docs/01-introducao-c/README.md
  docs/01-introducao-c/README.pdf
  docs/01-introducao-c/introducao.pdf
  docs/01-introducao-c/introducao_booleano.md
  docs/01-introducao-c/introducao_booleano.pdf
  docs/01-introducao-c/introducao_constante.md
  docs/01-introducao-c/introducao_constante.pdf
  docs/01-introducao-c/introducao_ponteiros.md
  docs/01-introducao-c/introducao_string_c.md
  docs/01-introducao-c/introducao_string_c.pdf
  docs/01-introducao-c/introducao_tipos_c.md
  docs/01-introducao-c/introducao_tipos_c.pdf
  docs/01-introducao-c/introducao_variaveis.md
  docs/01-introducao-c/introducao_variaveis.pdf
  docs/01-introducao-c/introdução_escopo.md
  docs/01-introducao-c/introdução_escopo.pdf
  docs/02-controle-fluxo/README.md
  docs/02-controle-fluxo/README.pdf
  docs/02-controle-fluxo/controle-fluxo-lacos.md
  docs/02-controle-fluxo/controle-fluxo-lacos.pdf
  docs/02-controle-fluxo/controle-fluxo.md
  docs/02-controle-fluxo/controle-fluxo.pdf
  docs/02-controle-fluxo/operadores-relacionais.md
  docs/02-controle-fluxo/operadores-relacionais.pdf
  docs/README.md
Labels: documentation

#8 Adiciona README com notas de aulas sobre introducao C
  docs/01-introducao-c/README.pdf
  src/01-introducao-c/README.md
  src/01-introducao-c/README.pdf
Labels: aula

#9 Feature/aula
  src/01-introducao-c/README.md
  src/01-introducao-c/README.pdf
Labels: aula

#10 Adiciona resposta exercicio cadastro
  src/01-introducao-c/README.md
  src/01-introducao-c/README.pdf
  src/01-introducao-c/aula02/exercicio/exercicioCadastro.c
Labels: bug
